application: anexablog
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:

- url: /
  script: main.app

- url: /usersignup
  script: usersignup.app

- url: /welcome
  script: usersignup.app

- url: /asciichan
  script: asciichan.app

- url: /blog
  script: blog.app

- url: /blog/newpost
  script: blog.app

- url: /blog/(\d+)
  script: blog.app

- url: /rot13
  script: rot13.app

- url: /css
  static_dir: css

- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.1"

- name: jinja2
  version: latest


